name: roll_call_app
description: 点到为止 - 让点名更有诗意
publish_to: 'none'
version: 1.6.1+73

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.19.0
  dynamic_color: 1.6.9
  # 自动更新功能依赖
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  confetti: ^0.8.0
  vibration: ^1.8.4
  share_plus: ^7.2.1
  file_picker: ^8.0.0+1
  lunar: ^1.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
